{"name": "Проверка невозможности авторизации пользователя при некорректных данных", "status": "passed", "steps": [{"name": "Регистрируем нового пользователя", "status": "passed", "start": 1734956991548, "stop": 1734956991703}, {"name": "Авторизуем пользователя с произвольными данными", "status": "passed", "parameters": [{"name": "email", "value": "'wtcunjjgsr@mail.comabc'"}, {"name": "password", "value": "'btarfxdnes'"}], "start": 1734956991703, "stop": 1734956991793}], "parameters": [{"name": "email_string", "value": "'abc'"}, {"name": "password_string", "value": "''"}], "start": 1734956991548, "stop": 1734956991794, "uuid": "edf84146-a29f-4eaf-a78b-515676eb9e94", "historyId": "d4ed988c783c74c722da77bf4248467d", "testCaseId": "ce64fdf58b6c86d2df175199085e4003", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_uncorrect_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "12380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}