{"name": "Проверка невозможности авторизации пользователя при некорректных данных", "status": "passed", "steps": [{"name": "Регистрируем нового пользователя", "status": "passed", "start": 1734956992557, "stop": 1734956992717}, {"name": "Авторизуем пользователя с произвольными данными", "status": "passed", "parameters": [{"name": "email", "value": "'xdpymxgfpy@mail.com'"}, {"name": "password", "value": "'tecggpcepgabc'"}], "start": 1734956992717, "stop": 1734956992876}], "parameters": [{"name": "email_string", "value": "''"}, {"name": "password_string", "value": "'abc'"}], "start": 1734956992557, "stop": 1734956992877, "uuid": "958dbee4-1eb9-4e9c-9bd6-091b5ea98e90", "historyId": "d4ed988c783c74c722da77bf4248467d", "testCaseId": "ce64fdf58b6c86d2df175199085e4003", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_uncorrect_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "12380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}